name : Github-Workflow
run-name : Github-Actions-Flow

on :
  push :
    branches :
    - master 
    - '!feature'
  pull_request :
    types : [opened, reopened]
    branches :
    - master 
    - feature
  issues :
    types : [opened, edited, milestoned]
    branches :
    - master
  workflow_dispatch :
  status :
#   schedule :
#   - cron : '*/20 * * * *'
  
jobs :
 build-stage :
 
  runs-on : test

  steps:
      - run: echo "Shell is $SHELL and OS is ${{ runner.os }}"

      - name: Checkout  repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

  # env :
  #       name : 'Rajesh'
  #       role : 'DevOps Engineer'
  
  # outputs:
  #   output1: ${{ steps.contents.outputs.test }}
        
  # strategy :
  #   matrix :
  #     version : [ 11 ]
  #     maven : [ 3.8.1 ]
      
  # steps :
  # - name : Checkout Stage
  #   uses: actions/checkout@v3
    
 #  - name: Set up JDK 1.8
 #    uses: actions/setup-java@v1
 #    with:
 #        java-version: ${{ matrix.version }}
    
 #  - name: Set up Maven
 #    uses: stCarolas/setup-maven@v4.4
 #    with:
 #        maven-version: ${{ matrix.maven }}
      
 #  - name: Build project with Maven
 #    run: mvn -B package --file pom.xml
    
 #  - name : Printing important Environment and Context
 #    run : |
 #          echo $GITHUB_API_URL	
 #          echo $GITHUB_ACTOR	
 #          echo $GITHUB_ACTION
 #          echo $GITHUB_ACTION_REPOSITORY	
 #          echo $GITHUB_PATH
 #          echo ${{ github. run_id }}

 #  - name: Cache local Maven repository
 #    uses: actions/cache@v2
 #    with:
 #      path: ~/.m2/repository
 #      key: ${{ runner.name }}-maven-${{ hashFiles('**/pom.xml') }}
      
 #  - name: Storing artifacts
 #    uses: actions/upload-artifact@v3
 #    with:
 #        name: myArtifacts
 #        path : .
 #        retention-days: 1
        
 # #  - name : Checker
 # #    if : ${{ job.status == 'success' }}
 # #    run : echo "Previous jobs are success"
        
 # #  - name : Creating a label
 # #    id : contents
 # #    run : |
 # #          echo "::set-output name=test::vitty"
  
 # # checking-out-value :

 # #    runs-on : self-hosted
 # #    if: ${{ success() }}
 # #    needs : build-stage
 # #    steps : 
    
 # #    - name : Printing values from other Jobs
 # #      run : |
 # #            echo ${{ needs.build-stage.outputs.output1 }}
          
 # # Running-shell :
 # #  runs-on : self-hosted
 # #  defaults :
 # #    run :
 # #        working-directory : /home/ubuntu/
 # #        shell : bash
 # #  steps :
  
 # #  - name : Running Shell Script
 # #    run : |
 # #          sh /home/ubuntu/shelly.sh
 # #          ls -lrt > output.txt 
        
        
        
        
              
    
    
  
  

  
  
  
