name : github-actions-workflow

run-name : github-actions-runname

on :
  
  push : 
    branches :
    - master
  
  workflow_dispatch :

env :
  
  name : Rajesh 

jobs :
  
  checking-context-values :
    
    runs-on : ubuntu-latest
    
    steps :
      
    - name : Checking out the Repository
      uses : actions/checkout@v3
      
    - name : Printing the environment value
      run :  echo " my name is $name "


  
  
  
  
  
  
  
  
  
  
  
