name : github-actions-workflow
run-name : github-actions-runname

on :  
  push : 
    branches :
    - master
  workflow_dispatch :

env :
  name : Rajesh 

jobs :

  checking-context-values :    
    
    strategy :
      matrix :
        version : [ ubuntu-latest , windows-latest ]
        
    runs-on : ${{ matrix.version }}
    
    steps :
    - name : Checking out the Repository
      uses : actions/checkout@v3
    - name : Printing the environment value
      run :  echo " my name is $name "
      shell : bash
    - name : Printing Github Contexts 
      run : |
            echo $GITHUB_TOKEN
            echo ${{ toJson(github.ref)   }}
            echo ${{ secrets.GITHUB_TOKEN }} 
    
    
    
    
    
    
    
    
    
    
    
    
